### ISSUE TITLE
Will this be updated to version 3.05 or 4.x ?

### ISSUE THREAD

**Issue by osos** [syncfusion/SfTesseract#1]
The libtesseract shipping with SyncFusion essentials is this rather old 3.02.

When is this expected to be updated to latest tesseract engine?

**Comment by praveenHari24** [comment]
Hi,

We have tested the Tesseract version 3.04 and found a lot of performance lag in our OCR processing, so we have maintained our tesseract source with 3.02. Upgrading to Tesseract 4.0 is purely based on our success of performance and quality test. Once after success in testing OCR processing with the latest version of tesseract, we will upgrade to Tesseract 4.0 and we will update you.

Note: Tesseract 4.0 is in alpha.

https://github.com/tesseract-ocr/tesseract/wiki/ReleaseNotes#to-be-released-as-v400---hopefully-in-2017h2
https://github.com/tesseract-ocr/tesseract/wiki/4.0-with-LSTM

Regards,
Praveen
